### ISSUE TITLE
REVIEW

### ISSUE THREAD

**Issue by ValeriiKupyna** [TolyaRuban/PhoneReactApp#1]
1. Наявні лишні відступи
2. незрозуміло чому сортeвання, і фільтрування відбуваються в сервісі який призначений для роботи з API

class Main extends React.Component
1. Ніяких side ефектів в конструкторі бути не має
2. (addItem)  що таке? називай зміні зрозуміло а не просто буквами\
3. Мені здається так набагото зрозуміліше `
addItem = (phone) => {
  this.setState((prevState) => ({
      phoneAdded: {
        ...this.state.phoneAdded,
        [phone]: prevState.phoneAdded[phone] ? prevState.phoneAdded[phone] : 1
      }
    }))
  };`

4. (queryChange ): Шо за аsync awayt для  setState? і для чого timeout ?
5. видали консоль лог

6. не використовуй індекс для ключів

**Comment by TolyaRuban** [comment]
2. перенес фильтр в Main

class Main extends React.Component

1. убрал
2. переименовал, некоторые другие тоже
4. убрал и написал как ты сказал, но проблема осталась
5. оставил один, чтоб ты понял, о чем я говорю

**Comment by TolyaRuban** [comment]
2. переместил фильтр в Main
class Main extends React.Component
1. +
2. переименовал ее и еще несколько других
4. таймаут был для как debounce 
5. +
